stages:
  - lint
  - typecheck
  - test
  - compatibility

lint:
  stage: lint
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install ruff
  script:
    - ruff check --config=pyproject.toml src/

typecheck:
  stage: typecheck
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install mypy
  script:
    - mypy --config-file=pyproject.toml src/

test:
  stage: test
  image: python:3.12
  before_script:
    - pip install --upgrade pip
    - pip install pytest pytest-asyncio
  script:
    - pytest -v

compatibility:
  stage: compatibility
  image: python:3.13
  before_script:
    - pip install --upgrade pip
    - pip install vermin
  script:
    - vermin --eval-annotations --backport typing --no-parse-comments .