repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.12
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --config=pyproject.toml ]
      files: ^src/

    # Run the formatter.
    - id: ruff-format
      args: [ --config=pyproject.toml ]
      files: ^src/

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
    # Run mypy type checking.
    - id: mypy
      args: [--config-file=pyproject.toml ]
      files: ^src/


- repo: https://github.com/christophmeissner/pytest-pre-commit
  rev: 1.0.0
  hooks:
  - id: pytest
    args: [ -v ]