repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.12
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --config=pyproject.toml, ./src/ ]

    # Run the formatter.
    - id: ruff-format
      args: [ --config=pyproject.toml, ./src/  ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
    # Run the type checker.
    - id: mypy
      args: [ --config-file=pyproject.toml, --explicit-package-bases, ./src/ ]
