site_name: uv template
repo_url: https://github.com/python-boilerplate/uv-template
repo_name: python-boilerplate/uv-template

nav:
  - Home:
    - Overview: index.md
    - Changelog: home/changelog.md
    - License: home/license.md
    - Contributing: home/contributing.md
  - Usage:
    - Options: usage/options.md
    - Commands: usage/commands.md
  - Features:
    - Overview: features/index.md
    - Python:
      - Python 3.10+: features/python.md
    - UV: features/uv.md
    - Docker: features/docker.md
    - CI/CD:
      - GitHub Actions: features/ci/github_actions.md
      - GitLab CI: features/ci/gitlab_ci.md
    - Dev Containers: features/devcontainers.md
    - Code Quality:
      - Ruff: features/code_quality/ruff.md
      - MyPy: features/code_quality/mypy.md
      - Pytest: features/code_quality/pytest.md
      - Vermin: features/code_quality/vermin.md
    - Pre-commit Hooks: features/pre-commit.md
    - Commitizen: features/commitizen.md
    - Environment Management: features/environment.md
    - MkDocs: features/mkdocs.md
    - Makefile: features/makefile.md
  - Reference:
    - Project Structure: reference/project_structure.md

theme:
  name: material
  features:
    - navigation.footer
    - navigation.tabs
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference


plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences