name: Lint & Check Types & Test

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ruff mypy pytest pytest-asyncio
      - name: Lint (ruff)
        run: ruff check --config=pyproject.toml src/
      - name: Type check (mypy)
        run: mypy --config-file=pyproject.toml src/
      - name: Run tests (pytest)
        run: pytest -v
